### ISSUE TITLE
[BUG] fvm flutter doctor -v tries to write in the normal non fvm flutter SDK folder

### ISSUE THREAD

**Issue by Wissperwind** [fluttertools/fvm#427]
Hi

- I discovered fvm
- I installed it
- I executed fvm install 3.0.0
- I executed fvm flutter doctor -v

 But it does not work:
```
fvm flutter doctor -v
Flutter failed to write to a file at "C:\path\to\my\non\fvm\flutter\version". The flutter tool cannot access the file or directory.
Please ensure that the SDK and/or project is installed in a location that has read/write permissions for the current user.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1      _throwFileSystemException (package:flutter_tools/src/base/error_handling_io.dart:820:3)
#2      _handleWindowsException (package:flutter_tools/src/base/error_handling_io.dart:810:3)
#3      _runSync (package:flutter_tools/src/base/error_handling_io.dart:605:7)
#4      ErrorHandlingFile.writeAsStringSync (package:flutter_tools/src/base/error_handling_io.dart:270:5)
#5      FlutterVersion.ensureVersionFile (package:flutter_tools/src/version.dart:162:74)
#6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:244:32)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     main (package:flutter_tools/executable.dart:94:3)
<asynchronous suspension>

```

Can't I used a regulary installed flutter and a fvm flutter in parallel?

**Comment by leoafarias** [comment]
@Wissperwind you have installed the flutter version, even though this is a weird error, can you try doing a `fvm use 3.0.0` to make sure its linked to the project. If that issue persists please do a `fvm doctor` so I can take a look at the output
